version: '3.8'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: database-wordpress.cgrqa20q0xnf.us-east-1.rds.amazonaws.com
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: minhasenha123
      WORDPRESS_DB_NAME: database-wordpress
    volumes:
      - /mnt/efs:/var/www/html/wp-content
